### ISSUE TITLE
Getting "y" when attempting to rename sandbox

### ISSUE THREAD

**Issue by jdgregson** [sandboxie/sandboxie#22]
Whenever I attempt to rename a sandbox, Sandboxie continuously enters 'y', preventing me from entering any sort of useful name.

![2020-05-22_15-45-41](https://user-images.githubusercontent.com/3778841/82714487-abf62a80-9c43-11ea-9df6-2d1fedde2f12.gif)

**Comment by DavidXanatos** [comment]
I can not confirm that issue, are you sure its not a problem with your keyboard?

**Comment by jdgregson** [comment]
I took a closer look and found that this was the result of an AutoHotKey script to send "y" to Explorer's Rename dialog triggered when you change a file extension. I further refined the script to not trigger on this dialog as well.
