### ISSUE TITLE
kmdutil create service  error 1078 when install

### ISSUE THREAD

**Issue by nikita-tarasov3** [sandboxie/sandboxie#30]
kmdutil create service  error 1078 when install. how to fix?

**Comment by DavidXanatos** [comment]
hmm... 
1. reboot your windows
2. get the zip release with the SandMan.exe
3. start sandman when it asks for admin rights or to setup something say no/cancel
4. when the UI opens go to sandbox -> maintenance -> stop all here allow admin rights
5. sandbox -> maintenance -> advanced -> ... uninstall service and uninstall driver, here also

whats next depands on what do you want, to install the regular release, now just run the installer again
if you want to run it standalone, clock on sandbox -> maintenance -> connect, and alow admin rights, the connect options automatically, whenneeded installs and starts the driver and service

Also check if no antivirus is blocking the SbieDrv.sys file as its signed with a leaked certificate some Anti-malware fools complain and block the file.

**Comment by nikita-tarasov3** [comment]
> hmm...
> 
> 1. reboot your windows
> 2. get the zip release with the SandMan.exe from the other repo: https://github.com/sandboxie-plus/Sandboxie/releases
> 3. start sandman when it asks for admin rights or to setup something say no/cancel
> 4. when the UI opens go to sandbox -> maintenance -> stop all here allow admin rights
> 5. sandbox -> maintenance -> advanced -> ... uninstall service and uninstall driver, here also
> 6. intall sandboxie again

Thanks! I found reason: i installed self-designed driver not included in project.
