### ISSUE TITLE
what's with 64bit version?

### ISSUE THREAD

**Issue by seisdr** [sandboxie/sandboxie#49]
```
ameer@localhost:~# wine64 SandboxieInstall64-533-3.exe
0024:err:plugplay:deviceloop_thread Can't init SDL: Could not initialize UDEV
002d:err:module:__wine_process_init L"Z:\\root\\SandboxieInstall64-533-3.exe" not supported on this system
```
uname -a
```
Linux localhost 3.10.86-g0c14827 #2 SMP PREEMPT Thu Jul 12 13:13:34 CST 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by smiley** [comment]
Sandboxie doesn't run on Linux or any win32 translation layers for it (I.e.: WINE, CrossOver, etc.).

**Comment by smiley** [comment]
Sandboxie is a kernel-based sandoxing environment for Windows and deeply coupled with it, it doesn't run on Linux or any win32 translation layers for it (I.e.: WINE, CrossOver, etc.).

**Comment by seisdr** [comment]
Ok I'm in need of containers on restricted environment thought this would help
