### ISSUE TITLE
IME not work in version 5.33.3

### ISSUE THREAD

**Issue by StoneMoe** [sandboxie/sandboxie#52]
IME not work in current latest release
Sandboxie version: 5.33.3
Windows version: Windows 10 Pro Workstation, version 2004, os version 19041.450

**Comment by Lyoko-Jeremie** [comment]
same .

**Comment by 44670** [comment]
same, IME is workable before I upgrade to win10 2004.

**Comment by skygunner** [comment]
https://github.com/sandboxie-plus/Sandboxie/issues/120

**Comment by Flowers704** [comment]
Your Post Is Best I Like It And I Like Love It<a href="https://crackwebs.com/sandboxie-
crack-latest-version/">Sandboxie 5.33.3 Crack</a>

**Comment by StoneMoe** [comment]
choose anyone of the methods below to solve this problem:
1. Switch to SandboxPlus and enable "Template_Windows10CoreUI" in template setting.
2. Enable MSIME's "Compatible mode"
