### ISSUE TITLE
BSOD KERNEL_SECURITY_CHECK_FAILURE when CORE ISOLATION is enabled

### ISSUE THREAD

**Issue by fusionneur** [sandboxie/sandboxie#72]
I am getting a BSOD with message : KERNEL_SECURITY_CHECK_FAILURE when Windows 10's CORE ISOLATION (memory integrity) is enabled under uefi/secure boot/tpm bitlocker encrypted.

I tried re-installing sandboxie after enabling memory integrity as well, but whenever i try to run a program from sandboxie it crashes the whole system.

**Comment by DavidXanatos** [comment]
This issue will be fixed in the next build: https://github.com/sandboxie-plus/Sandboxie/issues/221

**Comment by fusionneur** [comment]
thank you . sorry for posting here the issue. now i realized it was the wrong repo
