### ISSUE TITLE
Sandboxie error sbie2314 canceling process start.exe

### ISSUE THREAD

**Issue by rightofway** [sandboxie/sandboxie#84]
Heya im new to this Github site ,
 but have been using sandboxie for around 6years and have always used it to the point where the dump folder grows over 40gb untill i can be bother to delete it.  and lose bookmarks in firefox(then back them up to re load) 
. I very rarely have any issuis with this software only the odd windows update but can always find a work around to fix it . i have a new error message and i have tryed everything window did a update last night which seasm to be the main casue i have tryed to restore points with no luck.   i hope some one can help meh fix this issuss i mainily use firefox sandbox , also updated to the newest version also didnt fix said problem. i have deleted all contents of the sandbox defalut box and even made a 2nd sandbox to see if that would solve said iussis with no luck. run as admin also didnt work.

 error message is :- SBIE2101 Object name not found: \Sessions\1\BaseNamedObjects\SM0:10752:304:WilStaging_02, error CreateMutant (C0000022) access=001F0001 initialized=1
SBIE2314 Canceling process Start.exe [10752 / 7]

![sandboxie error problem](https://user-images.githubusercontent.com/105598628/168482418-8f5a7b75-caa7-4189-a613-56a94c50bfb0.png)

i run windows 10 , 500ssd  boot drive , 1tb hdd that is on its last legs only use it as read drive which even that as slow now (about 360gb of data on it)  AMD ryzen 5 2600 40gb ram 2 x 16gb ddr4 3200 + old 8gb ddr4 stick amd radeon rx 570 8gb
Windows 10, version 21H2
sandboxie verison 5.33.6 64bit
sandboxie config settings 

 [GlobalSettings]

Template=WindowsRasMan
Template=WindowsLive

Template=OfficeLicensing
ForceDisableSeconds=10
AlertProcess=firefox.exe

[UserSettings_0C3E0211]

SbieCtrl_UserName=james
SbieCtrl_NextUpdateCheck=1613945540
SbieCtrl_UpdateCheckNotify=n
SbieCtrl_ShowWelcome=n
SbieCtrl_WindowCoords=757,395,1238,558
SbieCtrl_ActiveView=40021
SbieCtrl_RecoverTarget=C:\Users\right\Desktop
SbieCtrl_SaveRecoverTargets=y
SbieCtrl_AutoApplySettings=n
SbieCtrl_BoxExpandedView=DefaultBox

[DefaultBox]

ConfigLevel=7
AutoRecover=y
BlockNetworkFiles=y
Template=qWave
Template=WindowsFontCache
Template=BlockPorts
Template=LingerPrograms
Template=Chrome_Phishing_DirectAccess
Template=Firefox_Phishing_DirectAccess
Template=AutoRecoverIgnore
RecoverFolder=%{374DE290-123F-4565-9164-39C4925E467B}%
RecoverFolder=%Personal%
RecoverFolder=%Favorites%
RecoverFolder=%Desktop%
BorderColor=#00FFFF,ttl
Enabled=y

Still hopefull someone will be able 2 fix this issus or help me find a fix  soon .

**Comment by DavidXanatos** [comment]
The old sandboxie is not compatible with windows update KB5011831 
you will need to switch to a newer build: https://github.com/sandboxie-plus/Sandboxie/releases

**Comment by rightofway** [comment]
cheers bud fixxed , i take it when i tryed to update it before was a problem with that update download didnt cong right.  i do love this program 10/10 and thanks for fast respond .

**Comment by LPeisen** [comment]
邮件已经收到，尽快给您回复。

**Comment by LPeisen** [comment]
邮件已经收到，尽快给您回复。
